<?php
/**
 * @file
 * taxonomy2.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function taxonomy2_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-archived-field_full_name'.
  $field_instances['taxonomy_term-archived-field_full_name'] = array(
    'bundle' => 'archived',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Add the full name of the ministers= here.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_full_name',
    'label' => 'Full name',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'taxonomy_term-collections-field_date_and_time'.
  $field_instances['taxonomy_term-collections-field_date_and_time'] = array(
    'bundle' => 'collections',
    'deleted' => 0,
    'description' => 'Add a date for the collection.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'long',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
          'show_remaining_days' => FALSE,
        ),
        'type' => 'date_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_date_and_time',
    'label' => 'Date and time',
    'required' => 0,
    'settings' => array(
      'default_value' => 'now',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'increment' => 15,
        'input_format' => 'd/m/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'text_parts' => array(),
        'year_range' => '-3:+3',
      ),
      'type' => 'date_popup',
      'weight' => 42,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_crest'.
  $field_instances['taxonomy_term-ministers-field_crest'] = array(
    'bundle' => 'ministers',
    'deleted' => 0,
    'description' => 'Add a crest image for the individual minister here.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_crest',
    'label' => 'Crest',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '500KB',
      'max_resolution' => '560x100',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_full_name'.
  $field_instances['taxonomy_term-ministers-field_full_name'] = array(
    'bundle' => 'ministers',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the full name of the minister here. Note that this is different from the \'Name\', which ought to be only one word.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_full_name',
    'label' => 'Full name',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_image'.
  $field_instances['taxonomy_term-ministers-field_image'] = array(
    'bundle' => 'ministers',
    'deleted' => 0,
    'description' => 'Upload an image of the minister here.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_image',
    'label' => 'Image',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '500KB',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_order'.
  $field_instances['taxonomy_term-ministers-field_order'] = array(
    'bundle' => 'ministers',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_order',
    'label' => 'Order',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_responsibilities'.
  $field_instances['taxonomy_term-ministers-field_responsibilities'] = array(
    'bundle' => 'ministers',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the repsonsibilities this minister holds. You can enter more than one line.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_responsibilities',
    'label' => 'Responsibilities',
    'required' => 1,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ministers-field_url'.
  $field_instances['taxonomy_term-ministers-field_url'] = array(
    'bundle' => 'ministers',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'A link to the minister\'s APH biography and page.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_url',
    'label' => 'APH Link',
    'required' => 1,
    'settings' => array(
      'absolute_url' => 1,
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'default',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'none',
      'title_label_use_field_label' => FALSE,
      'title_maxlength' => 128,
      'title_value' => '[node:title]',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('A link to the minister\'s APH biography and page.');
  t('APH Link');
  t('Add a crest image for the individual minister here.');
  t('Add a date for the collection.');
  t('Add the full name of the ministers= here.');
  t('Crest');
  t('Date and time');
  t('Enter the full name of the minister here. Note that this is different from the \'Name\', which ought to be only one word.');
  t('Enter the repsonsibilities this minister holds. You can enter more than one line.');
  t('Full name');
  t('Image');
  t('Order');
  t('Responsibilities');
  t('Upload an image of the minister here.');

  return $field_instances;
}
